### PR TITLE
Fix AuthDataDataSource

### LINKED ISSUE #77: Fix AuthDataDataSource
## Overview
when read blank value and convert Json via moshi, app crashed.

moshi can not convert blank to null

### PR DESCRIPTION
**Pull request by halu5071**
## Issue
- close #77

(From now on, I can sign commit with GPG.... wow)

### CODE REVIEW

File: halu5071/app/src/main/java/io/moatwel/github/presentation/di/NetworkModule.kt [hunk 1]
```diff
@@ -86,6 +87,7 @@ class NetworkModule {
     return Moshi.Builder()
       .add(KotlinJsonAdapterFactory())
       .add(AppJsonAdapterFactory.INSTANCE)
+      .add(EventJsonAdapter.FACTORY)
```
Comment (halubot) [inline halu5071/app/src/main/java/io/moatwel/github/presentation/di/NetworkModule.kt:90]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/halu5071/git-push-hackathon/blob/deee817a8a909a39c643f9e3c98accd208cb10fe/halu5071/app/src/main/java/io/moatwel/github/presentation/di/NetworkModule.kt#L90"></span>Unexpected indentation (2) (it should be 4)</td>
    </tr>
  </tbody>
</table>
